### ISSUE TITLE
对中文文档里的链接等未做判断，要求「://」为全角

### ISSUE THREAD

**Issue by mozii** [huntzhan/zhlint#2]
==================================================
E201: 只有中文或中英文混排中，一律使用中文全角标点
==================================================
LINE: 23
从 http://www.baidu.com

**Comment by huntzhan** [comment]
谢谢，我知道是什么问题了，回去休一下

**Comment by huntzhan** [comment]
@mozii 已修复发布，可以直接 `pip install -U zhlint` 更新
